### PR TITLE
Add VecGrowScan

### PR DESCRIPTION
**Pull request by meithecatte**
As discussed, this PR adds `VecGrowScan`, which supports insertions in addition to removals.

### CODE REVIEW

**Comment by jix** [comment]
Thank you! At first glance, this looks good to me. I hope to find some time to fully review it later today.

**Comment by jix** [comment]
I'm happy with the new API, even `replace_with_many_with` doesn't seem so bad in context. Regarding the implementation I only found one issue: I would expect the following test to pass:
```rust
    #[test]
    fn drop_after_partial_scan_with_inserts() {
        let mut nums = vec![1, 2, 5, 6];
        let mut scan = VecGrowScan::new(&mut nums);

        while let Some(mut value) = scan.next() {
            if *value > 2 {
                value.insert_many_before([3, 4].iter().copied());
                break;
            }
        }

        drop(scan);

        assert_eq!(nums, [1, 2, 3, 4, 5, 6]);
    }
```
In general, I think a few more tests would be useful, e.g. for the `_with` methods.

In any case the code needs to be formatted with `cargo +nightly fmt` (stable rustfmt will also do if there are no imports to merge) or CI will complain.

**Comment by meithecatte** [comment]
Whew, thanks for catching that partial scan bug! I added some tests and ran rustfmt on each commit.

**Review by jix — COMMENTED** [review]
r+

**Pull request merged**
